### ISSUE TITLE
Alignment on mobile 

### ISSUE THREAD

**Issue by trunghieud** [block-core/blockcore-website#3]
This is using Safari mobile. I think About and Links make it really busy. I suggest to remove it. What do you guys think? 
![A566A859-5C32-45B9-A533-45771C4CE7A1](https://user-images.githubusercontent.com/29716420/73313972-8ac78500-41e1-11ea-8d60-e7977223a44e.jpeg)

**Comment by miladsoft** [comment]
A good blockchain like blockcore requires a good website. I am proud to design a very good site with great UI and UX and dedicate it to my dear friends who are developing blockcore.

**Comment by sondreb** [comment]
The "About" and "Links" was previously removed. The footer might still feel a bit cluttered, but the font size and icon sizes has been scaled down a bit too in the coming update.
